dist: xenial
os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

matrix:
  exclude:
    - compiler: gcc
      os: osx

addons:
  apt:
    sources:
    - llvm-toolchain-xenial-7
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - clang-7
    - libhwloc-dev
    - mesa-utils
    - freeglut3-dev

  homebrew:
    packages:
    - cmake
    - hwloc
    - llvm

before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      LLVM=/usr/local/opt/llvm;
      export CC=$LLVM/bin/clang;
      export CXX=$LLVM/bin/clang++;
      export CFLAGS=-I$LLVM/include;
      export CXXFLAGS=-I$LLVM/include;
      export LDFLAGS=-L$LLVM/lib;
    elif [ $CC = "clang" ]; then
      export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH;
    fi

install:
  - $CXX --version
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - bin/trinity -h
